on: 
  pull_request:
    branches:
      - master
name: Build apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    # Tests would be added later
    # - run: flutter test
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/app/outputs/apk/release/app-release.apk